---
title: "Publications"
---
## Publications
<div class="apa">

Hoogeveen, S., Berkhout, S. W., Gronau, Q. F., Wagenmakers, E.-J., & Haaf, J. M. (2023). 
Improving Statistical Analysis in Team Science: The Case of a Bayesian Multiverse of Many Labs 4. 
<i>Advances in Methods and Practices in Psychological Science, 6</i>(3). 
<a href="https://doi.org/10.1177/25152459231182318" target="_blank">https://doi.org/10.1177/25152459231182318</a>

Berkhout, S. W., Schuurman, N. K., & Hamaker, E. L. (2023). 
A tool to simulate and visualize dyadic interaction dynamics. 
<i>Psychological Methods</i>. 
<a href="https://doi.org/10.1037/met0000575" target="_blank">https://doi.org/10.1037/met0000575</a>

Berkhout, S. W., Haaf, J. M., Gronau, Q. F., Heck, D. W., & Wagenmakers, E.-J. (2023). 
A tutorial on Bayesian model-averaged meta-analysis in JASP. <i>Behavior Research Methods. </i>
<a href="https://doi.org/10.3758/s13428-023-02093-6" target="_blank"><https://doi.org/10.3758/s13428-023-02093-6</a>

Gronau, Q. F., Heck, D. W., Berkhout, S. W., Haaf, J. M., & Wagenmakers, E.-J. (2021). 
A Primer on Bayesian Model-Averaged Meta-Analysis. 
<i>Advances in Methods and Practices in Psychological Science, 4</i>(3). 
<a href="https://doi.org/10.1177/25152459211031256" target="_blank">https://doi.org/10.1177/25152459211031256</a>

</div>

#### Blog posts
<div class="apa">

Gronau, Q. F., Heck, D., Berkhout, S. W., Haaf, J. M., & Wagenmakers, E. (2020, 7th May). 
A Primer on Bayesian Model-Averaged Meta-Analysis. <i>Bayesian Spectacles.</i> 
<a href="https://www.bayesianspectacles.org/a-primer-on-bayesian-model-averaged-meta-analysis/" target="_blank">
https://www.bayesianspectacles.org/a-primer-on-bayesian-model-averaged-meta-analysis/</a>

Berkhout, S. W., Haaf, J. M., Gronau, Q. F., Heck, D., & Wagenmakers, E. (2020, 12th May). 
How to Conduct a Bayesian Model-Averaged Meta-Analysis in JASP. <i>JASP Blog.</i>
<a href="https://jasp-stats.org/2020/05/12/how-to-conduct-a-bayesian-model-averaged-meta-analysis-in-jasp/" target="_blank">
https://jasp-stats.org/2020/05/12/how-to-conduct-a-bayesian-model-averaged-meta-analysis-in-jasp/</a>

</div>
